from merit.bootstrap.mir_composite_parity import (
    MIR_COMPOSITE_KIND_BINARY,
    MIR_COMPOSITE_KIND_BINDING,
    MIR_COMPOSITE_KIND_CALL,
    MIR_COMPOSITE_KIND_CONST,
    MIR_COMPOSITE_KIND_CONSTRUCT,
    MIR_COMPOSITE_KIND_FIELD,
    MIR_COMPOSITE_KIND_OPERAND,
)
from merit.bootstrap.mir_function_assembly_parity import (
    MIR_ASSEMBLY_SOURCE_KIND_BODY,
    MIR_ASSEMBLY_SOURCE_KIND_CONTRACT,
    MIR_ASSEMBLY_SOURCE_KIND_OWNERSHIP,
    MIR_CONTRACT_PHASE_OLD_SNAPSHOT,
    MIR_CONTRACT_PHASE_POSTCONDITION,
    MIR_CONTRACT_PHASE_PRECONDITION,
    MIR_CONTRACT_KIND_BINARY,
    MIR_CONTRACT_KIND_CALL,
    MIR_CONTRACT_KIND_CHECK,
    MIR_CONTRACT_KIND_CONST,
    MIR_CONTRACT_KIND_FIELD_LOAD,
    MIR_CONTRACT_KIND_OLD_SNAPSHOT,
    MIR_CONTRACT_KIND_RESULT_CAPTURE,
    MIR_CONTRACT_KIND_TEMPORARY_LOCAL,
)
from merit.bootstrap.mir_function_ownership_assembly_parity import (
    MIR_OWNERSHIP_RECORD_KIND_ACTIVATE,
    MIR_OWNERSHIP_RECORD_KIND_DROP,
    MIR_OWNERSHIP_RECORD_KIND_IMPLICIT_DROP,
    MIR_OWNERSHIP_RECORD_KIND_MOVE,
    MIR_OWNERSHIP_RECORD_KIND_NESTED_TRANSFER,
    MIR_OWNERSHIP_RECORD_KIND_REPLACE_DROP,
    MIR_OWNERSHIP_RECORD_KIND_REPLACE_MOVE,
    MIR_OWNERSHIP_STATE_DROPPED,
    MIR_OWNERSHIP_STATE_LIVE,
    MIR_OWNERSHIP_STATE_MOVED,
    MIR_OWNERSHIP_STATE_UNINITIALIZED,
)
from merit.bootstrap.mir_function_parity import (
    MIR_FUNCTION_KIND_BINARY,
    MIR_FUNCTION_KIND_CALL,
    MIR_FUNCTION_KIND_CALL_ARGUMENT,
    MIR_FUNCTION_KIND_CONST,
    MIR_FUNCTION_KIND_COPY_TO_BINDING,
    MIR_FUNCTION_KIND_ENUM_CONSTRUCT,
    MIR_FUNCTION_KIND_ENUM_PAYLOAD_LOAD,
    MIR_FUNCTION_KIND_ENUM_TAG_LOAD,
    MIR_FUNCTION_KIND_FUNCTION,
    MIR_FUNCTION_KIND_PARAMETER,
    MIR_FUNCTION_KIND_PRINT,
    MIR_FUNCTION_KIND_RETURN,
    MIR_FUNCTION_KIND_SOURCE_LOCAL,
    MIR_FUNCTION_KIND_STRUCT_CONSTRUCT,
    MIR_FUNCTION_KIND_STRUCT_FIELD_LOAD,
    MIR_FUNCTION_KIND_STRUCT_FIELD_STORE,
    MIR_FUNCTION_KIND_TEMPORARY,
)
from merit.bootstrap.mir_generic_parity import (
    MIR_GENERIC_KIND_CALL,
    MIR_GENERIC_KIND_CONST,
    MIR_GENERIC_KIND_OPERAND,
)
from merit.bootstrap.mir_parity import (
    MIR_EXPRESSION_KIND_BINARY,
    MIR_EXPRESSION_KIND_BINDING,
    MIR_EXPRESSION_KIND_CONST,
    MIR_EXPRESSION_KIND_GROUP_ALIAS,
)


def test_python_mir_kind_mirrors_preserve_bootstrap_encodings():
    assert (
        MIR_EXPRESSION_KIND_CONST,
        MIR_EXPRESSION_KIND_BINARY,
        MIR_EXPRESSION_KIND_GROUP_ALIAS,
        MIR_EXPRESSION_KIND_BINDING,
    ) == (1, 2, 3, 4)
    assert (
        MIR_COMPOSITE_KIND_CONST,
        MIR_COMPOSITE_KIND_BINARY,
        MIR_COMPOSITE_KIND_BINDING,
        MIR_COMPOSITE_KIND_CALL,
        MIR_COMPOSITE_KIND_FIELD,
        MIR_COMPOSITE_KIND_CONSTRUCT,
        MIR_COMPOSITE_KIND_OPERAND,
    ) == tuple(range(1, 8))
    assert (
        MIR_FUNCTION_KIND_FUNCTION,
        MIR_FUNCTION_KIND_SOURCE_LOCAL,
        MIR_FUNCTION_KIND_TEMPORARY,
        MIR_FUNCTION_KIND_CONST,
        MIR_FUNCTION_KIND_BINARY,
        MIR_FUNCTION_KIND_COPY_TO_BINDING,
        MIR_FUNCTION_KIND_RETURN,
        MIR_FUNCTION_KIND_PRINT,
        MIR_FUNCTION_KIND_ENUM_CONSTRUCT,
        MIR_FUNCTION_KIND_ENUM_TAG_LOAD,
        MIR_FUNCTION_KIND_ENUM_PAYLOAD_LOAD,
        MIR_FUNCTION_KIND_STRUCT_CONSTRUCT,
        MIR_FUNCTION_KIND_STRUCT_FIELD_LOAD,
        MIR_FUNCTION_KIND_STRUCT_FIELD_STORE,
        MIR_FUNCTION_KIND_PARAMETER,
        MIR_FUNCTION_KIND_CALL,
        MIR_FUNCTION_KIND_CALL_ARGUMENT,
    ) == tuple(range(1, 18))
    assert (
        MIR_GENERIC_KIND_CONST,
        MIR_GENERIC_KIND_CALL,
        MIR_GENERIC_KIND_OPERAND,
    ) == (1, 2, 3)
    assert (
        MIR_CONTRACT_KIND_TEMPORARY_LOCAL,
        MIR_CONTRACT_KIND_CONST,
        MIR_CONTRACT_KIND_BINARY,
        MIR_CONTRACT_KIND_CHECK,
        MIR_CONTRACT_KIND_CALL,
        MIR_CONTRACT_KIND_RESULT_CAPTURE,
        MIR_CONTRACT_KIND_FIELD_LOAD,
        MIR_CONTRACT_KIND_OLD_SNAPSHOT,
    ) == tuple(range(1, 9))
    assert (
        MIR_ASSEMBLY_SOURCE_KIND_CONTRACT,
        MIR_ASSEMBLY_SOURCE_KIND_BODY,
        MIR_ASSEMBLY_SOURCE_KIND_OWNERSHIP,
    ) == (1, 2, 3)
    assert (
        MIR_CONTRACT_PHASE_PRECONDITION,
        MIR_CONTRACT_PHASE_POSTCONDITION,
        MIR_CONTRACT_PHASE_OLD_SNAPSHOT,
    ) == (1, 2, 3)
    assert (
        MIR_OWNERSHIP_RECORD_KIND_ACTIVATE,
        MIR_OWNERSHIP_RECORD_KIND_MOVE,
        MIR_OWNERSHIP_RECORD_KIND_DROP,
        MIR_OWNERSHIP_RECORD_KIND_REPLACE_DROP,
        MIR_OWNERSHIP_RECORD_KIND_REPLACE_MOVE,
        MIR_OWNERSHIP_RECORD_KIND_IMPLICIT_DROP,
        MIR_OWNERSHIP_RECORD_KIND_NESTED_TRANSFER,
    ) == tuple(range(1, 8))
    assert (
        MIR_OWNERSHIP_STATE_UNINITIALIZED,
        MIR_OWNERSHIP_STATE_LIVE,
        MIR_OWNERSHIP_STATE_MOVED,
        MIR_OWNERSHIP_STATE_DROPPED,
    ) == tuple(range(4))
