from __future__ import annotations

import argparse
import re
from pathlib import Path

from merit.copybook import CopybookError, CopybookSchema, parse_copybook


def _c_ident(name: str) -> str:
    ident = re.sub(r"[^A-Za-z0-9]+", "_", name).strip("_").lower() or "record"
    if ident[0].isdigit():
        ident = "f_" + ident
    return ident


def _macro(name: str) -> str:
    ident = re.sub(r"[^A-Za-z0-9]+", "_", name).strip("_").upper() or "RECORD"
    if ident[0].isdigit():
        ident = "F_" + ident
    return ident


def generate_c_header(schema: CopybookSchema, *, prefix: str = "merit_cobol") -> str:
    """Generate a raw-byte C ABI descriptor; never alias COBOL bytes as C fields."""
    p = _c_ident(prefix)
    P = _macro(prefix)
    record = _c_ident(schema.name)
    R = _macro(schema.name)
    type_name = f"{p}_{record}_bytes"
    guard = f"{P}_{R}_H"
    lines = [
        "/* Generated by merit-copybook. Raw COBOL bytes only: no host-layout aliasing. */",
        f"#ifndef {guard}",
        f"#define {guard}",
        "",
        "#include <stddef.h>",
        "#include <stdint.h>",
        "",
        f"#define {P}_{R}_RECORD_LENGTH {schema.record_length}u",
        "",
        f"typedef struct {type_name} {{",
        f"    uint8_t bytes[{P}_{R}_RECORD_LENGTH];",
        f"}} {type_name};",
        "",
    ]
    for field in schema.fields:
        F = _macro(field.name)
        lines.extend([
            f"#define {P}_{R}_{F}_OFFSET {field.offset}u",
            f"#define {P}_{R}_{F}_ELEMENT_LENGTH {field.length}u",
            f"#define {P}_{R}_{F}_OCCURS {field.occurs}u",
            f"#define {P}_{R}_{F}_STORAGE_LENGTH {field.length * field.occurs}u",
            "",
        ])
    lines.extend([
        f"static inline const uint8_t *{p}_{record}_field_const(",
        f"    const {type_name} *record_bytes, size_t offset)",
        "{",
        "    return record_bytes->bytes + offset;",
        "}",
        "",
        f"static inline uint8_t *{p}_{record}_field(",
        f"    {type_name} *record_bytes, size_t offset)",
        "{",
        "    return record_bytes->bytes + offset;",
        "}",
        "",
        f"#endif /* {guard} */",
        "",
    ])
    return "\n".join(lines)


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(
        prog="merit-copybook-c",
        description="Generate a C raw-record descriptor for an audited COBOL adapter",
    )
    parser.add_argument("copybook", type=Path)
    parser.add_argument("--prefix", default="merit_cobol")
    args = parser.parse_args(argv)
    try:
        schema = parse_copybook(args.copybook.read_text(encoding="utf-8"), name=args.copybook.stem)
        print(generate_c_header(schema, prefix=args.prefix), end="")
        return 0
    except (CopybookError, OSError) as exc:
        parser.error(str(exc))
    return 2


if __name__ == "__main__":
    raise SystemExit(main())
